name: release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: DudeWheresMyScore

      - name: Create Release Zipfile
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r DudeWheresMyScore.zip DudeWheresMyScore

      - uses: actions/upload-artifact@v2
        with:
          name: DudeWheresMyScore.zip
